steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - beta
      - run
      - deploy
      - annict
      - --project=vital-reef-492404-f7
      - --region=asia-northeast1
      - --source=.
      - --function=Annict
      - --base-image=python314
      - --domain=annict.penguincabinet.com
      - --set-secrets=annict-badge-key=annict-badge-key:latest
      - --quiet
options:
  logging: CLOUD_LOGGING_ONLY
